//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backup_Project {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Multicolor LED module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MulticolorLED multicolorLED;
        
        /// <summary>The Reflector module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.VolkswagenBildungsinstitutGmbH.Reflector reflector;
        
        /// <summary>The PollSwitch module using socket 14 of the mainboard.</summary>
        private Gadgeteer.Modules.VolkswagenBildungsinstitutGmbH.PollSwitch pollSwitch;
        
        /// <summary>The Distance US3 module using socket 12 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.DistanceUS3 distanceUS3;
        
        /// <summary>The MotorControllerL298 module using socket 8 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.MotorControllerL298 motorControllerL298;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZSpiderII Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZSpiderII)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpiderII();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.multicolorLED = new GTM.GHIElectronics.MulticolorLED(5);
            this.reflector = new GTM.VolkswagenBildungsinstitutGmbH.Reflector(9);
            this.pollSwitch = new GTM.VolkswagenBildungsinstitutGmbH.PollSwitch(14);
            this.distanceUS3 = new GTM.GHIElectronics.DistanceUS3(12);
            this.motorControllerL298 = new GTM.GHIElectronics.MotorControllerL298(8);
        }
    }
}
